name: Deploy the static files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: images
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Replace version string
      run: |
        sed -i "s/version=latest/version=$GITHUB_SHA/g" webapp/index.html
        sed -i "s/version=latest/version=$GITHUB_SHA/g" webapp/app.js
      env:
        GITHUB_CONTEXT: ${{ github.sha }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webapp
