name: Deploy the static files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: "?version=latest"
        replace: "?version=$GITHUB_SHA"
        include: "public/index.html"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
