name: Deploy the static files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Replace version string
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "version=latest"
        replace: "version=$GITHUB_CONTEXT"
        include: "public/index.html"
      env:
        GITHUB_CONTEXT: ${{ github.sha }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
